amcl:
  ros__parameters:
    use_sim_time: True
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.8
    alpha4: 0.2
    alpha5: 0.1
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    scan_topic: "scan"
    min_particles: 500
    max_particles: 2000

map_server:
  ros__parameters:
    use_sim_time: True
    yaml_filename: "/home/romain/create3_ws/install/create3_navigation_task/share/create3_navigation_task/config/empty_map.yaml"

controller_server:
  ros__parameters:
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      critics: ["ObstacleFootprintCritic", "GoalDistCritic", "PathAlignCritic"]
      debug_trajectory_details: true

planner_server:
  ros__parameters:
    use_sim_time: True
    expected_planner_frequency: 10.0

bt_navigator:
  ros__parameters:
    use_sim_time: True

lifecycle_manager:
  ros__parameters:
    use_sim_time: True
    autostart: True
    node_names:
      - "controller_server"
      - "planner_server"
      - "recoveries_server"
      - "bt_navigator"
